### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by kubilaycaglayan** [frankopkusianwar/restaurant-javascript#2]
Hello Frank :wave: 
Thank you very much for your presentation.
In your [menu](https://github.com/frankopkusianwar/restaurant-javascript/blob/develop/src/components/menu4.js) file you have repeating code blocks like :arrow_down: 
```
  const cardDiv1 = document.createElement('div');
  cardDiv1.setAttribute('class', 'card');
  cardDiv1.setAttribute('style', 'width: 18rem;');
```
:bulb: Instead, you may have a method that does this work for you, and you can use that method in any part of your project.
```
function createElementWithClassAndStyle(tag, className, style) {
  const element = document.createElement(tag);
  element.setAttribute('class', className);
  element.setAttribute('style', style);
  return element;
}

const cardDiv1 = createElementWithClassAndStyle('div', 'card', 'width: 18rem;')
```

You can also check my repository [HERE](https://github.com/kubilaycaglayan/restaurant/blob/restaurant/src/myLib.js) to see an implementation of these helpers.

With all my respect...

**Comment by mariosknl** [comment]
Great project Frank. You can probably try to create a file with the elements that you are grabbing from DOM. Also, you can try to separate your code in different sections for better readability.
